# ~/.config/starship.toml

"$schema" = 'https://starship.rs/config-schema.json'
format = """$os$username$hostname$kubernetes$directory$git_branch$nodejs$python"""

# Drop ugly default prompt chars
[character]
success_symbol = ''
error_symbol = ''

[os]
format = '[$symbol](bold white) '   
disabled = false

[os.symbols]
Windows = ' '
Arch = '󰣇'
Ubuntu = ''
Macos = '󰀵'

# Modules

[directory]
home_symbol = ' ~'
read_only_style = '197'
read_only = ''
format = 'at [$path]($style)[$read_only]($read_only_style) '

[git_branch]
symbol = ' '
format = 'via [$symbol$branch]($style) '
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold #FFA500'

[username]
style_user = 'yellow bold'
disabled = false
style_root = 'black bold'
format = '[$user]($style) '
show_always = true

[nodejs]
symbol = ' '
